// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright  Google LLC

// snippet.show
import GoogleCloudWkt
import GoogleType
import GoogleIamV1
import Foundation

func sample(client: some IAMPolicy) async throws {
  let response = try await client.testIamPermissions(
    request: TestIamPermissionsRequest( /* set fields */)
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleIamV1.Clients.IAMPolicyClient()
      try await sample(client: client)
    } catch {
      print("Error: \(error)")
    }
  }
}
