// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt
import GoogleType

/// One delta entry for AuditConfig. Each individual change (only one
/// exempted_member in each entry) to a AuditConfig will be a separate entry.
public struct AuditConfigDelta: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The action that was performed on an audit configuration in a policy.
  /// Required
  public var action: AuditConfigDelta.Action

  /// Specifies a service that was configured for Cloud Audit Logging.
  /// For example, `storage.googleapis.com`, `cloudsql.googleapis.com`.
  /// `allServices` is a special value that covers all services.
  /// Required
  public var service: String

  /// A single identity that is exempted from "data access" audit
  /// logging for the `service` specified above.
  /// Follows the same format of Binding.members.
  public var exemptedMember: String

  /// Specifies the log_type that was be enabled. ADMIN_ACTIVITY is always
  /// enabled, and cannot be configured.
  /// Required
  public var logType: String

  /// Initialize a new instance of `AuditConfigDelta`.
  public init(
    action: AuditConfigDelta.Action = AuditConfigDelta.Action(),
    service: String = String(),
    exemptedMember: String = String(),
    logType: String = String(),
  ) {
    self.action = action
    self.service = service
    self.exemptedMember = exemptedMember
    self.logType = logType
  }

  /// The type of action performed on an audit configuration in a policy.
  public enum Action: Int, Codable, Equatable, Sendable {
    case unspecified = 0
    case add = 1
    case remove = 2

    public init() {
      self = .unspecified
    }

    public var stringValue: String {
      switch self {
      case .unspecified: return "ACTION_UNSPECIFIED"
      case .add: return "ADD"
      case .remove: return "REMOVE"
      }
    }

    public init?(stringValue: String) {
      switch stringValue {
      case "ACTION_UNSPECIFIED": self = .unspecified
      case "ADD": self = .add
      case "REMOVE": self = .remove
      default: return nil
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.iam.v1.AuditConfigDelta"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
