// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt
import GoogleType

/// Provides the configuration for logging a type of permissions.
/// Example:
///
///     {
///       "audit_log_configs": [
///         {
///           "log_type": "DATA_READ",
///           "exempted_members": [
///             "user:jose@example.com"
///           ]
///         },
///         {
///           "log_type": "DATA_WRITE"
///         }
///       ]
///     }
///
/// This enables 'DATA_READ' and 'DATA_WRITE' logging, while exempting
/// jose@example.com from DATA_READ logging.
public struct AuditLogConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
  /// The log type that this config enables.
  public var logType: AuditLogConfig.LogType

  /// Specifies the identities that do not cause logging for this type of
  /// permission.
  /// Follows the same format of
  /// [Binding.members][google.iam.v1.Binding.members].
  ///
  /// [google.iam.v1.Binding.members]: <doc:Binding/members>
  public var exemptedMembers: [String]

  /// Initialize a new instance of `AuditLogConfig`.
  public init(
    logType: AuditLogConfig.LogType = AuditLogConfig.LogType(),
    exemptedMembers: [String] = [],
  ) {
    self.logType = logType
    self.exemptedMembers = exemptedMembers
  }

  /// The list of valid permission types for which logging can be configured.
  /// Admin writes are always logged, and are not configurable.
  public enum LogType: Int, Codable, Equatable, Sendable {
    case unspecified = 0
    case adminRead = 1
    case dataWrite = 2
    case dataRead = 3

    public init() {
      self = .unspecified
    }

    public var stringValue: String {
      switch self {
      case .unspecified: return "LOG_TYPE_UNSPECIFIED"
      case .adminRead: return "ADMIN_READ"
      case .dataWrite: return "DATA_WRITE"
      case .dataRead: return "DATA_READ"
      }
    }

    public init?(stringValue: String) {
      switch stringValue {
      case "LOG_TYPE_UNSPECIFIED": self = .unspecified
      case "ADMIN_READ": self = .adminRead
      case "DATA_WRITE": self = .dataWrite
      case "DATA_READ": self = .dataRead
      default: return nil
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.iam.v1.AuditLogConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
