// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt
import GoogleType

/// One delta entry for Binding. Each individual change (only one member in each
/// entry) to a binding will be a separate entry.
public struct BindingDelta: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
  /// The action that was performed on a Binding.
  /// Required
  public var action: BindingDelta.Action

  /// Role that is assigned to `members`.
  /// For example, `roles/viewer`, `roles/editor`, or `roles/owner`.
  /// Required
  public var role: String

  /// A single identity requesting access for a Google Cloud resource.
  /// Follows the same format of Binding.members.
  /// Required
  public var member: String

  /// The condition that is associated with this binding.
  public var condition: GoogleType.Expr?

  /// Initialize a new instance of `BindingDelta`.
  public init(
    action: BindingDelta.Action = BindingDelta.Action(),
    role: String = String(),
    member: String = String(),
    condition: GoogleType.Expr? = nil,
  ) {
    self.action = action
    self.role = role
    self.member = member
    self.condition = condition
  }

  /// The type of action performed on a Binding in a policy.
  public enum Action: Int, Codable, Equatable, Sendable {
    case unspecified = 0
    case add = 1
    case remove = 2

    public init() {
      self = .unspecified
    }

    public var stringValue: String {
      switch self {
      case .unspecified: return "ACTION_UNSPECIFIED"
      case .add: return "ADD"
      case .remove: return "REMOVE"
      }
    }

    public init?(stringValue: String) {
      switch stringValue {
      case "ACTION_UNSPECIFIED": self = .unspecified
      case "ADD": self = .add
      case "REMOVE": self = .remove
      default: return nil
      }
    }
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.iam.v1.BindingDelta" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
