// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax

import GoogleCloudWkt
import GoogleType

/// API Overview
///
/// Manages Identity and Access Management (IAM) policies.
///
/// Any implementation of an API that offers access control features
/// implements the google.iam.v1.IAMPolicy interface.
///
/// ## Data model
///
/// Access control is applied when a principal (user or service account), takes
/// some action on a resource exposed by a service. Resources, identified by
/// URI-like names, are the unit of access control specification. Service
/// implementations can choose the granularity of access control and the
/// supported permissions for their resources.
/// For example one database service may allow access control to be
/// specified only at the Table level, whereas another might allow access control
/// to also be specified at the Column level.
///
/// ## Policy Structure
///
/// See google.iam.v1.Policy
///
/// This is intentionally not a CRUD style API because access control policies
/// are created and deleted implicitly with the resources to which they are
/// attached.
///
/// @Snippet(id: "IAMPolicyQuickstart")
public class IAMPolicy {
  let inner: GoogleCloudGax.HTTPClient

  /// Creates a new `IAMPolicy` instance.
  public init(
    endpoint: String? = nil,
    credentials: GoogleCloudAuth.Credentials? = nil,
    session: URLSession? = nil,
  ) throws {
    let endpoint = endpoint ?? "https://iam-meta-api.googleapis.com"
    self.inner = try HTTPClient(endpoint: endpoint, credentials: credentials, session: session)
  }

  /// Sets the access control policy on the specified resource. Replaces any
  /// existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
  public func setIamPolicy(request: SetIamPolicyRequest) async throws
    -> Policy
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.resource as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try JSONDecoder().decode(Policy.self, from: data)
  }

  /// Gets the access control policy for a resource.
  /// Returns an empty policy if the resource exists and does not have a policy
  /// set.
  public func getIamPolicy(request: GetIamPolicyRequest) async throws
    -> Policy
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.resource as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try JSONDecoder().decode(Policy.self, from: data)
  }

  /// Returns permissions that a caller has on the specified resource.
  /// If the resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  public func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> TestIamPermissionsResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.resource as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try JSONDecoder().decode(TestIamPermissionsResponse.self, from: data)
  }
}
