// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Output-only policy member strings of a Google Cloud resource's built-in
/// identity.
public struct ResourcePolicyMember: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// IAM policy binding member referring to a Google Cloud resource by
  /// user-assigned name (https://google.aip.dev/122). If a resource is deleted
  /// and recreated with the same name, the binding will be applicable to the new
  /// resource.
  ///
  /// Example:
  /// `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
  public var iamPolicyNamePrincipal: String

  /// IAM policy binding member referring to a Google Cloud resource by
  /// system-assigned unique identifier (https://google.aip.dev/148#uid). If a
  /// resource is deleted and recreated with the same name, the binding will not
  /// be applicable to the new resource
  ///
  /// Example:
  /// `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
  public var iamPolicyUidPrincipal: String

  /// Initialize a new instance of `ResourcePolicyMember`.
  public init(
    iamPolicyNamePrincipal: String = String(),
    iamPolicyUidPrincipal: String = String(),
  ) {
    self.iamPolicyNamePrincipal = iamPolicyNamePrincipal
    self.iamPolicyUidPrincipal = iamPolicyUidPrincipal
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.iam.v1.ResourcePolicyMember"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
