// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Output-only policy member strings of a Google Cloud resource's built-in
/// identity.
public struct ResourcePolicyMember: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// IAM policy binding member referring to a Google Cloud resource by
  /// user-assigned name (https://google.aip.dev/122). If a resource is deleted
  /// and recreated with the same name, the binding will be applicable to the new
  /// resource.
  ///
  /// Example:
  /// `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
  public var iamPolicyNamePrincipal: Swift.String = Swift.String()

  /// IAM policy binding member referring to a Google Cloud resource by
  /// system-assigned unique identifier (https://google.aip.dev/148#uid). If a
  /// resource is deleted and recreated with the same name, the binding will not
  /// be applicable to the new resource
  ///
  /// Example:
  /// `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
  public var iamPolicyUidPrincipal: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourcePolicyMember`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourcePolicyMember().with { $0.iamPolicyNamePrincipal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let iamPolicyNamePrincipal = CodingKeys(stringValue: "iamPolicyNamePrincipal")
    static let iamPolicyUidPrincipal = CodingKeys(stringValue: "iamPolicyUidPrincipal")

    static let _knownKeys: Set<Swift.String> = [
      "iamPolicyNamePrincipal",
      "iamPolicyUidPrincipal",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .iamPolicyNamePrincipal)
    {
      self.iamPolicyNamePrincipal = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .iamPolicyUidPrincipal)
    {
      self.iamPolicyUidPrincipal = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.iamPolicyNamePrincipal, forKey: .iamPolicyNamePrincipal)
    try container.encode(self.iamPolicyUidPrincipal, forKey: .iamPolicyUidPrincipal)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v1.ResourcePolicyMember"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
